spring:
  application:
    name: architecture-zuul
  cloud:
    loadbalancer:
      retry:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka

zuul:
  routes:
    api-user:
      path: /user-service/**
      serviceId: architecture-userservice
    api-coupon:
      path: /coupon-service/**
      serviceId: architecture-couponservice
  authFilter:
    ignoreUrl: /user-service/login