spring:
  application:
    name: architecture-couponservice
  #redis集群配置
  redis:
    pool:
      jedis:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10
        # 连接池中的最大空闲连接
        max-idle: 50
        # 连接池中的最小空闲连接
        min-idle: 50
        # 连接超时时间（毫秒）
      timeout: 60000
      #集群
    cluster:
      max-redirects: 6
      nodes: 172.20.10.8:7000,172.20.10.8:7001,172.20.10.9:7000,172.20.10.9:7001, 172.20.10.10:7000,172.20.10.10:7001

  cloud:
    loadbalancer:
      retry:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka

##断路器超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#配置打开断路器
feign:
  hystrix:
    enabled: true
#提高通信效率
  compression:
    request:
      min-request-size: 2048
      mime-types: text/html, application/xml, application/json
#turbine
turbine:
  app-config: architecture-orderservice,architecture-userservic
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")

